#!/bin/bash

 Version=1.04
  Myname="${0##*/}"

:<<'DOC'
= anacal - calculation of chemical composition from elemental analysis results

= Synopsis
anacal [options] file[.ea] [max_dev]	

== Options
-s	use the short format
-w	in the short format, report weight instead of mole fractions
-h	prints this help
-H	prints full documentation

= Description
Given, for a chemical composition:
- the elemental percentages for (some of the) elements and
- a set of bruto formulae, one for each possible component 
anacal calculates compositions with one or more of the formula's
resulting in a good (that is: better than a certain standard deviation) fit
between calculated and experimental element percentages. 

Input is taken from |file.ea|, output is written to |stdout|.
The extension .ea is automatically appended to the input file.

Run without parameters for help.

= Input
The input file should have the following structure (numbers are line
numbers):
1	a title line
2	elementsymbol followed by percentage for each element determined
3+	bruto formula's of the possible components, one per line;
	comments may be added with the #-character;
	remaining characters up to end-of-line are skipped.

Sample input file (case sensitive):

   6718 DEBO 145
   C54.53 H6.31 N8.10 S14.48
   C15 H20 N2 O3 S
   C11 H16 N2 O S
   C4 H12 N2 S2
   C2 H4 O S
   S	#sulphur
   H Cl	#hydrochloric acid
   H2 O	#water

= Author
[Wybo Dekker](wybo@dekkerdocumenten.nl)

= Copyright
Released under the [GNU General Public License](www.gnu.org/copyleft/gpl.html)
DOC

# used and created on-the-fly - declare for shellcheck: 
REd=''

    die() { local i; for i; do Bla "$Myname: $REd$i"; done 1>&2; exit 1; }
helpsrt() { sed -n '/^= Synopsis/,/^= /p' "$0"|sed '1d;$d'; exit; }

# shellcheck disable=SC2154
helpall() { sed -n "/^:<<'DOC'$/,/^DOC/p" "$0"|sed -n '1d;$d;p'|
            less -Ps"$Myname-${Version/./·} documentation - type h for help, q to quit."
		exit
	  }

_colnames=(Bla Red Gre Yel Blu Mag Cya Whi)
:<<'DOC' #------ function _setxtcolor --------------------------------------------
= _setxtcolor
parameters	1 index in _colnames array
		2 true for light false for dark variant
		3 true for bold false for normal variant
description	Explanation by example:
		Creates a variable Red, which contains the ANSI-code for red.
		Also creates variables REd for light red, ReD for bold red, and 
		RED for light bold red.
		Finally, also creates functions with the same names, which print
		their arguments, each on a new line, in the corresponding color. 
		If these functions have three arguments, and the first is 'on',
		the second argument is interpreted as the color for the background.
		So |YEL on Blu string| print the string in light bold yellow on a 
		blue background. Of course, bold has no meaning for a background
		color, therefore a capitalized third letter in a background color
		is translated to blinking.
		Examples:
		  Red -> red
		  REd -> light red
		  RED -> light bold red
		  Red on Yel -> red on yellow
		  Red on YEl -> red on light yellow
		  Red on YEL -> blinking red on light yellow
		  RED on YeL -> blinking light bold red on yellow
globals  set:	  base dir ext 
globals used:	  IFS PWD altdir
returns:	0 on succes, 1 otherwise
DOC
#-------------------------------------------------------------------------------
_setxtcolor(){ # color (0-7), light, bold
   local name=${_colnames[$1]} l=$1 b='' foo
   if $2; then name=$(foo=${name:1};echo "${name:0:1}${foo^}"); (( l+=8 )); fi
   if $3; then name=$(foo=${name:2};echo "${name:0:2}${foo^}"); b='1;'; fi
   eval "$name() {
     local on='' i
     if [[ \$1 == on ]]; then
        eval on=\\\$\$2
        on=\${on/38/48}
        on=\${on/1;48/5;48}
        shift 2
     fi
     for i; do 
        printf \"\$$name\$on %s[0m\\n\" \"\$i\"
     done
   }
   $name=\"[${b}38;5;${l}m\";"
}

:<<'DOC' #------ function nocolor --------------------------------------------
= nocolor
parameters:	-
description:	Unsets any variable created by |docolor|
globals  set:	All variables in array colnames + upper case variants
globals used:	  _colnames
returns:	0
DOC
#-------------------------------------------------------------------------------
nocolor() { local i p q r
   for i in "${_colnames[@]}"; do
      p=${i:0:1} q=${i:1:1} r=${i:2:1}
      eval "$i='' $p${q^}$r='' $p$q${r^}='' $p${q^}${r^}=''" 
   done
}

:<<'DOC' #------ function docolor --------------------------------------------
= docolor
parameters:	-
description:	Create color variabels and functions
globals  set:	All variables in array colnames + upper case variants
globals used:	-
returns:	0
DOC
#-------------------------------------------------------------------------------
docolor() {
   local l b c
   for l in false true; do
      for b in false true; do
         for c in {0..7}; do
            _setxtcolor $c $l $b
         done
      done
   done
}

[[ -n $PREFIX ]] || die "envvar PREFIX is empty, must point to install dir"
[[ -w $PREFIX ]] || die "$PREFIX is not writable"
docolor

instscr() { 
   rm -f "$PREFIX/bin/$Myname"
   cp "$0" "$PREFIX/bin/$Myname"
   chmod 755 "$PREFIX/bin/$Myname"
   gendoc "$Myname"
   gendoc -m "$Myname"
   scriptinfo --markdown "$Myname" |sed 's/bash/C/' >README
   touch "$0".c
   make --quiet
   make --quiet clean
   mv "$PREFIX/bin/$Myname" anacal.script
   mv -f "$Myname" $PREFIX/bin
   mv anacal.script anacal
   cd ..
   exit 
}

if ! options=$(getopt \
   -n "$Myname" \
   -o IhHV \
   -- "$@"
); then exit 1; fi
eval set -- "$options"
while [ $# -gt 0 ]; do
   case $1 in
   (-I)  instscr;;
   (-V)  echo $Version; exit;;
   (-h)  helpsrt;;
   (-H)  helpall;;
   (--)  shift;  break;;
   (*)	         break;;
   esac
done

